### ISSUE TITLE
主题：完善自定义配色

### ISSUE THREAD

**Issue by RadarNyan** [RadarNyan/ElectronicObserver#10]
需要新增自定义的部分：
- [x] 任务：任务类型 ( 彩色背景 ) 上显示的文字色
- [x] 司令部：资源超过自然回复上限时的文字色 / 背景色
- [x] 司令部：舰娘、装备空位不满活动图出击限制时文字色 / 背景色
- [x] 工厂：建造完成文字色 / 背景色
- [x] 入渠：修理完成文字色 / 背景色
- [x] 战斗：特殊血条 ( MVP、已退避、受损 BOSS ) 文字色 / 背景色
- [x] 舰队一览：大破 / 大破进击、入渠结束、远征返回、疲劳恢复的文字色 / 背景色
- [x] 司令部：高速修复、高速建造、开发资材、改修资材达到 3,000 个时的文字色 / 背景色
- [x] 司令部：家具币达到 200,000 个时的文字色 / 背景色
- [x] 司令部：资源储量达到 300,000 时的文字色 / 背景色
- [x] 日志：已修改为 RichTextBox，实现了中日文字体区分

暂时不会添加的内容
菜单栏：需要自定义渲染器，过于复杂暂不添加

**Comment by Misaka00357** [comment]
舰队一览：出击中、远征中、就绪、未补给舰队背景色、文字色
工厂、入渠：完成或倒计时结束时闪烁的背景色、文字色
菜单栏背景色、文字色
分割线色

**Comment by RadarNyan** [comment]
除菜单栏外大致完成，暂时关闭此 issue
