### ISSUE TITLE
舰队信息：昼战炮击火力值不显示

### ISSUE THREAD

**Issue by frathy** [RadarNyan/ElectronicObserver#11]
昼战炮击火力值不显示

**Comment by RadarNyan** [comment]
原版 BUG，应该已经修复。
可以尝试使用这个版本：( 未完全修复本次秋活 API 变化带来的问题，未对应 7 船舰队 )
https://ci.appveyor.com/project/RadarNyan/electronicobserver-5xd4a/build/2.8.2-dev3/artifacts

依然存在这个问题的话请 reopen issue 。
