### ISSUE TITLE
调整面板颜色

### ISSUE THREAD

**Issue by duelking** [RadarNyan/ElectronicObserver#8]
帖内说有三种预设颜色，请问是要到哪里调整呢？

**Comment by RadarNyan** [comment]
帖子最上面就写着呢……
> v2.4.4.1-m3 暗色主题已经基本完善，但默认主题为亮色且界面上暂无主题设置入口，可以通过手动编辑 Settings\Configuration.xml 修改 <ThemeID>0</ThemeID> 中的数字为 1 开启 ( 编辑配置文件前请退出 74EO，保存配置文件后启动 74EO 即生效 ) 另外将此数字设为 2 可以使用旧的 VS2012Light 主题 ( 和魔改版一样 )

**Comment by duelking** [comment]
感谢，问完几天后也看到
